### ISSUE TITLE
Groups.list limit default is too low

### ISSUE THREAD

**Issue by xanderjjj** [outofcoffee/slack-gateway#1]
https://github.com/outofcoffee/slack-gateway/blob/a7ad4494e6c12189a9c5671f3b2a52abc6a1a507/backends/slack/src/main/kotlin/com/gatehill/slackgateway/backend/slack/service/SlackOperationsService.kt#L72

When the groups.list function is invoked from the API, the default limit of the returned list can cause the results to be truncated, leading to the gateway attempting to recreate an already existing channel.

https://api.slack.com/methods/groups.list

**Comment by pcornish** [comment]
Thanks @xanderjjj. Looks like we'll need to make sure paging is working properly.

**Comment by outofcoffee** [comment]
Thanks @xanderjjj. Looks like we'll need to make sure paging is working properly.

**Comment by outofcoffee** [comment]
Work underway in branch `bug/paginated-list-queries`

**Comment by pcornish** [comment]
Fixed by #3

**Comment by outofcoffee** [comment]
Fixed by #3, released in v0.2.0
